const data = {
  stocks: [
    {
      currency: "USD",
      description: "Blonder Tongue Laboratories Inc",
      displaySymbol: "BDR",
      figi: "BBG000FVBVT2",
      isin: null,
      mic: "XASE",
      shareClassFIGI: "BBG001S8NC34",
      symbol: "BDR",
      symbol2: "",
      type: "Common Stock",
    },
    {
      currency: "USD",
      description: "Magnolia Oil and Gas Corporation",
      displaySymbol: "MGY",
      figi: "BBG00GNC8DL2",
      isin: null,
      mic: "XNYS",
      shareClassFIGI: "BBG00GNC8DM1",
      symbol: "MGY",
      symbol2: "",
      type: "Common Stock",
    },
    {
      currency: "USD",
      description: "iShares Russell Mid Cap Growth",
      displaySymbol: "IWP",
      figi: "BBG000BW05W9",
      isin: null,
      mic: "ARCX",
      shareClassFIGI: "BBG001S561Z8",
      symbol: "IWP",
      symbol2: "",
      type: "ETP",
    },
    {
      currency: "USD",
      description: "Ivivi Technologies Inc",
      displaySymbol: "IVVI",
      figi: "BBG000HTG4P4",
      isin: null,
      mic: "OOTC",
      shareClassFIGI: "BBG001SP98H6",
      symbol: "IVVI",
      symbol2: "",
      type: "Common Stock",
    },
    {
      currency: "USD",
      description: "K S Holdings Corporation",
      displaySymbol: "KSHOF",
      figi: "BBG00SRLNG92",
      isin: null,
      mic: "OOTC",
      shareClassFIGI: "BBG001S6JFC6",
      symbol: "KSHOF",
      symbol2: "",
      type: "Common Stock",
    },
  ],
};

export default data;

// const data = {
//   exchanges: [
//     {
//       name: "OSEBX",
//       index: 841.42,
//       change: 1.54,
//     },
//     {
//       name: "Frankfurt DAX",
//       index: 841.42,
//       change: 1.54,
//     },
//     {
//       name: "Euronext 100",
//       index: 841.42,
//       change: 1.54,
//     },
//     {
//       name: "Hang Seng",
//       index: 841.42,
//       change: 1.54,
//     },
//   ],
//   stocks: [
//     {
//       name: "Veidekke",
//       ticker: "VEI",
//       bid: 128.5,
//       ask: 129.0,
//       sector: "Industry",
//       change: 1.54,
//       dividends: {
//         2020: 20,
//         2019: 19,
//         2018: 18,
//         2017: 15,
//         2016: 13,
//         2015: 10,
//         2014: 12,
//         2013: 15,
//         2012: 10,
//         2011: 15,
//         2010: 12,
//         2009: 3,
//         2008: 5,
//         2007: 12,
//         2006: 15,
//         2005: 5,
//         2004: 3,
//       },
//       homepage: "https://google.com",
//       investorpage: "https://google.com",
//       pe: 15,
//       research: [
//         {
//           title: "First research",
//           description:
//             "This is the description. It is usually a lot longer than the title and contains information about the research that has been done",
//           link: "https://google.com",
//           author: { name: "Jake", authorId: "author123" },
//           id: 1,
//         },
//       ],
//     },
//     {
//       name: "Aker",
//       ticker: "AKER",
//       bid: 128.5,
//       ask: 129.0,
//       sector: "Industry",
//       change: 1.54,
//       dividends: {
//         2020: 23,
//         2019: 5,
//         2018: 18,
//         2017: 15,
//         2016: 13,
//         2015: 10,
//       },
//       homepage: "https://google.com",
//       investorpage: "https://google.com",
//       pe: 15,
//       research: [
//         {
//           title: "First research",
//           description:
//             "This is the description. It is usually a lot longer than the title and contains information about the research that has been done",
//           link: "https://google.com",
//           author: { name: "Jake", authorId: "author123" },
//           id: 1,
//         },
//         {
//           title: "Second research",
//           description:
//             "This is the description. It is usually a lot longer than the title and contains information about the research that has been done",
//           link: "https://google.com",
//           author: { name: "Jake", authorId: "author123" },
//           id: 2,
//         },
//       ],
//     },
//     {
//       name: "Yara",
//       ticker: "YARA",
//       bid: 128.5,
//       ask: 129.0,
//       sector: "Industry",
//       change: 1.54,
//       dividends: {
//         2020: 13,
//         2019: 15,
//         2018: 18,
//         2017: 15,
//         2016: 13,
//         2015: 10,
//       },
//       homepage: "https://google.com",
//       investorpage: "https://google.com",
//       pe: 15,
//       research: [
//         {
//           title: "First research",
//           description:
//             "This is the description. It is usually a lot longer than the title and contains information about the research that has been done",
//           link: "https://google.com",
//           author: { name: "Jake", authorId: "author123" },
//           id: 1,
//         },
//       ],
//     },
//     {
//       name: "Leroy",
//       ticker: "LSG",
//       bid: 128.5,
//       ask: 129.0,
//       sector: "Industry",
//       change: 1.54,
//       dividends: {
//         2020: 2,
//         2019: 3,
//         2018: 18,
//         2017: 15,
//         2016: 13,
//         2015: 10,
//       },
//       homepage: "https://google.com",
//       investorpage: "https://google.com",
//       pe: 15,
//       research: [
//         {
//           title: "First research",
//           description:
//             "This is the description. It is usually a lot longer than the title and contains information about the research that has been done",
//           link: "https://google.com",
//           author: { name: "Jake", authorId: "author123" },
//           id: 1,
//         },
//       ],
//     },
//     {
//       name: "DNO ASA",
//       ticker: "DNO",
//       bid: 128.5,
//       ask: 129.0,
//       sector: "Industry",
//       change: 1.54,
//       dividends: {
//         2020: 0.2,
//         2019: 3,
//         2018: 18,
//         2017: 15,
//         2016: 13,
//         2015: 10,
//       },
//       homepage: "https://google.com",
//       investorpage: "https://google.com",
//       pe: 15,
//       research: [
//         {
//           title: "First research",
//           description:
//             "This is the description. It is usually a lot longer than the title and contains information about the research that has been done",
//           link: "https://google.com",
//           author: { name: "Jake", authorId: "author123" },
//           id: 1,
//         },
//       ],
//     },
//   ],
// };

// export default data;
